CDCgov/ReportVision

.gitignore
dedupe/record_linkage_testing/Dockerfile.api
dedupe/record_linkage_testing/Dockerfile.runner
dedupe/record_linkage_testing/README.md
dedupe/record_linkage_testing/compose.yml
dedupe/record_linkage_testing/scripts/test.sh
dedupe/record_linkage_testing/src/main.py

Add a `compose.yml` file and its dependencies to get a record linkage performance testing environment setup.
Fixes #9 
This PR attempts to achieve the following:
- initialize a docker compose environment with the 4 services necessary for running performance tests
- updates .gitignore with some standard rules for python projects
- monkey patches the linkage API container with OpenTelemetry instrumentation
- sets up a test runner container with the Synthea binary
- after initialization, runs a simple `test.sh` script to verify that the API is working and otel events are being gathered

record linkage performance testing docker compose

---

.github/workflows/issues-close-project-done.yaml

Changing the cron job time so the issue closing action runs less daily.
Currently, the action runs every 2 hours. That is not needed.

[IDWA-28] Fix cron job time to once a day, during weekdays - closing issues

---

.github/workflows/projects-auto-move-new-sprint.yml

I feel the best way to test this action without creating a new project is just to merge it into main and see if it works at 0500 on Thursday and it it doesn't we'll adjust and fix from there.
#98 

[IDWA-OCR-98] Auto Move Iterations Forward

---

OCR/frontend/src/componets/ExtractUploadFile.tsx

https://github.com/CDCgov/IDWA/issues/184
add structure to ingest template to local storage(see structure below)
make updates to dropdown.
pass data to the next page through route.
```
"templates": [
{
"name": "",
"description":"",
"pages": [
{
"image": "base64"
"fieldNames": []
}
]
}
]
```

Extract skeleton updates

---

OCR/frontend/e2e/App.spec.ts
OCR/frontend/playwright.config.ts
OCR/frontend/src/components/SortableTable/SortableTable.tsx
OCR/frontend/src/components/TemplatesIndex/TemplatesIndex.tsx

Fixes some comments in #230. 
- Remove React.Fragments that weren't needed
- Use JS default arguments in place of if statement in function body
- Remove unused imports added incorrectly by editor trying to be helpful
- Fixed timezone bug in E2E tests

Minor Cleanup of TemplateIndex

---

OCR/frontend/e2e/ReviewTemplate.spec.ts
OCR/frontend/src/components/EditableText/EditableText.scss
OCR/frontend/src/components/EditableText/EditableText.tsx
OCR/frontend/src/components/SortableTable/SortableTable.tsx
OCR/frontend/src/pages/ReviewTemplate.tsx
OCR/frontend/src/style/index.scss
OCR/frontend/tsconfig.app.json

- Adds the click to edit functions for the review and edit page
- Return will commit changes
- Escape will revert changes since last commit
- Clicking outside of the text box will commit changes
- If there are errors Submit button on review page will be disabled
- Hovering over content will display icon (transition of icon will respect
reduce motion preferences)
- Minor tsconfig tweak to remove error when importing
syntheticDefaultImports
- Use SortableTable on Review page
- Update SortableTable to pass formatter function (value, idx, row) to allow more complex formatting
- Fix bug with Sortable Table passing in wrong index to formatter
functions
Demo:

Add Click-To-Edit functionality

---

ops/terraform/config/dev.config
ops/terraform/config/dev2.config
ops/terraform/config/dev3.config
ops/terraform/config/dev4.config
ops/terraform/config/dev5.config
ops/terraform/config/dev6.config
ops/terraform/data.tf
ops/terraform/locals.tf
ops/terraform/main.tf
ops/terraform/modules/app_gateway/main.tf
ops/terraform/modules/app_gateway/variables.tf
ops/terraform/modules/app_service/main.tf
ops/terraform/modules/app_service/variables.tf
ops/terraform/modules/compute/variables.tf
ops/terraform/modules/container_instances/main.tf
ops/terraform/modules/container_instances/variables.tf
ops/terraform/modules/network/main.tf
ops/terraform/modules/network/outputs.tf
ops/terraform/modules/network/variables.tf
ops/terraform/modules/security/main.tf
ops/terraform/modules/security/variables.tf
ops/terraform/modules/storage/main.tf
ops/terraform/modules/storage/variables.tf
ops/terraform/providers.tf
ops/terraform/variables.tf

Right now names of resources are statically set and visible to the entire world, including our docker images. ~~We specifically need to do this with docker tags and image urls so we can deploy from GHA's~~

Terraform variable clean-up and creation

---

.github/workflows/build-deploy-frontend.yml
.github/workflows/build-deploy-ocr.yml
.github/workflows/deploy-dev.yml

We temporarily disabled the docker image checker cause it was bugging out, just to get the deployment automation moving forward. Now we have the time to fix it.

Fix docker image check for faster OCR deployments

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/ImageAnnotator.tsx
frontend/src/pages/AnnotateTemplate.tsx
frontend/src/pages/SaveTemplate.tsx
frontend/src/types/templates.ts
frontend/src/utils/functions.ts

Replaces local storage for intermediate storage during the new template flow. 
Does not replace storing of the final templates or the storage for extract flow (those are follow ups)
N/A
#391

Replace local storage with zustand for new template flow

---

frontend/api/api.ts
frontend/src/components/ReviewTable.scss
frontend/src/components/ReviewTable.tsx

Adds tool bar to extraction flow

fix(RV-447): Add toolbar to extraction flows

---

backend/dev-dockerfile
backend/src/main/resources/application.yaml
dev-env.yaml

Docker is not connecting to DB anymore. db params are updated to ensure db connection works.

added default db params to dev file (fix)

---

frontend/src/components/TemplatesIndex/TemplatesIndex.scss
frontend/src/components/TemplatesIndex/TemplatesIndex.tsx
frontend/src/hooks/use-pagination/index.ts
frontend/src/hooks/use-pagination/use-pagination.test.ts

fix(RV-394): Add pagination

---

ops/terraform/main.tf
ops/terraform/modules/app_service/variables.tf
ops/terraform/modules/database/main.tf
ops/terraform/modules/database/outputs.tf
ops/terraform/modules/database/variables.tf
ops/terraform/modules/network/main.tf
ops/terraform/modules/network/variables.tf
ops/terraform/modules/vault/main.tf
ops/terraform/modules/vault/outputs.tf
ops/terraform/modules/vault/variables.tf
ops/terraform/providers.tf
ops/terraform/variables.tf

Update database module to include the server id and fqdn and ensure that the credentials of the database can be accessible to the middleware-api module.  
* Also added the `azurerm_postgresql_flexible_server_firewall_rule` resource for added protection of the communication of the database and middleware app_service.
* Moved the retention delete provisions to the `azurerm_key_vault` resource and removing it from the `azurerm` provider features section.
#478 
- [ x ] The title of this PR is descriptive and concise.
- [ x ] My changes follow the style guidelines of this project.
- [ x ] I've let the team know about this PR by linking it in the review channel

Update Postgres DB and Add DB Variables to Middleware-Api

---

.github/workflows/build-deploy-frontend.yml
frontend/api/api.ts
frontend/src/types/templates.ts

- Remove extra slash in middleware endpoint
- Remove duplicate code
- Make the variable not have have a slash at the end for better readability
notice the double slashes

remove extra slash in middleware endpoint and clean up

---

ops/terraform/locals.tf
ops/terraform/main.tf
ops/terraform/modules/app_gateway/main.tf
ops/terraform/modules/app_gateway/variables.tf
ops/terraform/modules/network/main.tf
ops/terraform/modules/network/outputs.tf
ops/terraform/modules/network/variables.tf

Updated appgw with its own independent subnet and added Web Application Firewall (WAF) protections to provide added security for our end users and Azure resources.  The separate subnet resolved the error shown below.  This error resulted when we were using the load balancer subnet in our gateway configurations, causing conflicts when trying to deploy the appgw via terraform.
```
Error: creating Application Gateway (Subscription: "72d4d159-ba2c-4fee-82da-4ff96e9195cb"
│ Resource Group Name: "reportvision-rg-dev"
│ Application Gateway Name: "reportvision-appgateway-dev"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error: ApplicationGatewaySubnetCannotHaveOtherResources: Subnet /subscriptions/72d4d159-ba2c-4fee-82da-4ff96e9195cb/resourceGroups/reportvision-rg-dev/ …
```

update app gateway with separate network and add WAF protections

---

.github/actions/tf-setup/action.yml
.github/workflows/deploy-dev.yml

This appends needed vars for the `tfvars` file at CI/CD time.

Add new vars to Terraform environment from GHA

---

.github/workflows/build-deploy-frontend.yml
.github/workflows/build-deploy-middleware.yaml
.github/workflows/build-deploy-ocr.yml
.github/workflows/deploy-dev.yml

Remove Demo and fix backend path

---

frontend/package-lock.json
frontend/src/components/ExtractUploadFile.tsx
frontend/src/components/FileInput.tsx
frontend/src/components/FileInput/file-input.tsx
frontend/src/components/FileInput/file-preview.tsx
frontend/src/components/UploadFile.scss
frontend/src/components/UploadFile.tsx
frontend/src/pages/AnnotateTemplate.tsx
frontend/src/pages/__snapshots__/UploadTemplate.test.tsx.snap

fix(RV-428): Fix change upload flow to reflect UI

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/components/ExtractUploadFile.tsx
frontend/src/components/ReviewBulk.tsx
frontend/src/components/ReviewTable.tsx
frontend/src/contexts/ErrorContext.test.tsx
frontend/src/contexts/ErrorContext.tsx
frontend/src/error/ErrorBanner.scss
frontend/src/error/ErrorBanner.tsx
frontend/src/error/ErrorBoundary.test.tsx
frontend/src/error/ErrorBoundary.tsx
frontend/src/error/ErrorFallback.tsx
frontend/src/main.tsx
frontend/src/pages/ErrorPage.test.tsx
frontend/src/pages/ErrorPage.tsx
frontend/src/pages/ReviewTemplate.tsx

fix(RV-426): Adds error framework

---

README.md

Relocate Public Domain Standard Notice to the notice section and fix video rendering.

Relocate public domain notice and fix rendering video in root README

---

OCR/benchmark_main.py
OCR/ocr/api.py
OCR/ocr/services/alignment/backends/four_point_transform.py
OCR/ocr/services/alignment/backends/image_homography.py
OCR/ocr/services/alignment/backends/random_perspective_transform.py
OCR/ocr/services/alignment/image_alignment.py
OCR/ocr/services/batch_metrics.py
OCR/ocr/services/batch_segmentation.py
OCR/ocr/services/image_ocr.py
OCR/ocr/services/image_segmenter.py
OCR/ocr/services/metrics_analysis.py
OCR/ocr/services/phdc_converter/builder.py
OCR/ocr/services/phdc_converter/models.py
OCR/ocr/services/phdc_converter/phdc_converter.py
OCR/ocr/services/tesseract_ocr.py
OCR/pyproject.toml
OCR/tests/assets/ocr_metrics_test.py

Also, add lint checks to ensure that Google-style docstrings are enforced. There are a few exclusions, namely for test and test-related files, and the phdc_converter subdirectory which seems to not be used and is already documented in a different style.
https://github.com/CDCgov/ReportVision/issues/504

Document all functions in `ocr/` and add relevant type signatures
