CDCgov/ReportVision

.github/pull_request_template.md, REVIEW_GUIDELINES.md, REVIEW_SLAS.md
This PR aims to initiate a discussion to standardize our code review process, with the intention of incorporating agreed-upon artifacts to provide guidance for the team in the future.
The content herein is not meant to be definitive or anywhere near our team's desired outcome. Rather, it serves as an initial framework, incorporating widely-used boilerplate definitions available online, along with some insights drawn from my past team experiences.
**If anyone finds this initial framework too opinionated or inflexible, please let your lead(s) know.  Starting over is always an option.**
The documents within are as follows:
- **.github/pull_request_template.md**: A checklist template that will be used for all future pull requests, aiming to maintain consistency for both author(s) and …
=> code review documentation

OCR/README.md, OCR/tests/ocr_test.py
Cleanup and testing the PR checks
=> Remove unused import

.github/workflows/projects-auto-move-new-sprint.yml
=> Fix auto spring forward

.github/workflows/projects-auto-move-new-sprint.yml
=> Fix auto forward sprint to biweekly on wednesday

.github/workflows/ocr-benchmarks.yml
#136 
The live dashboard => https://cdcgov.github.io/IDWA/dev/bench/
=> Make the OCR Benchmark dashboard UI more customizable

.github/workflows/ocr-benchmarks.yml
=> fix error 2

.github/workflows/ocr-benchmarks.yml
=> just output of benchmark

OCR/ocr/main.py, OCR/ocr/services/image_ocr.py, OCR/tests/ocr_test.py
https://github.com/CDCgov/IDWA/issues/151
=> added confidence scores to OCR

OCR/frontend/.github/workflows/playwright.yml, OCR/frontend/.gitignore, OCR/frontend/README.md, OCR/frontend/e2e-examples/demo-todo-app.spec.ts, OCR/frontend/e2e/example.spec.ts, OCR/frontend/package-lock.json, OCR/frontend/package.json, OCR/frontend/playwright.config.ts
Add playwright for e2e support
#163 
=> add playwright for e2e tests

OCR/frontend/package.json, OCR/frontend/src/componets/FileInput.tsx, OCR/frontend/src/componets/FilePreview.test.tsx, OCR/frontend/src/componets/FilePreview.tsx, OCR/frontend/src/componets/Stepper.tsx, OCR/frontend/src/componets/UploadFile.tsx, OCR/frontend/src/componets/tests/UploadFile.test.tsx, OCR/frontend/src/contexts/FilesContesxt.test.tsx, OCR/frontend/src/contexts/FilesContext.tsx, OCR/frontend/src/main.tsx, OCR/frontend/src/pages/AnnotateTemplate.tsx, OCR/frontend/src/pages/UploadTemplate.test.tsx, OCR/frontend/src/utils/tests.tsx, OCR/frontend/yarn.lock
- wires up navigation to route `/new-template/annotate`
- creates Files Context
- updates unit tests
=> feat(No-id): Wire up files context and navigation

OCR/frontend/package-lock.json, OCR/frontend/package.json, OCR/frontend/src/componets/Header.tsx, OCR/frontend/src/componets/ImageAnnotator.tsx, OCR/frontend/src/main.tsx, OCR/frontend/src/pages/AnnotateTemplate.tsx, OCR/frontend/src/pages/UploadTemplate.tsx
- adds react imager package
- adds navigation to back and submit
- show image base 64
=> feat(no-id): Add pdf labeler

OCR/frontend/src/componets/ImageAnnotator.tsx
adds local storage persistance of pdf files 
[Story](https://github.com/CDCgov/IDWA/issues/167)
=> feat(No-id): Add local storage persistance

OCR/frontend/src/componets/ImageAnnotator.tsx, OCR/frontend/src/constants/labels.ts, OCR/frontend/src/contexts/AnnotationContext.test.tsx, OCR/frontend/src/contexts/AnnotationContext.tsx, OCR/frontend/src/main.tsx, OCR/frontend/src/pages/AnnotateTemplate.scss, OCR/frontend/src/pages/AnnotateTemplate.tsx
- adds micro interactions
- unit tests for context setting
#190 
=> feat(190): Add micro interactions

OCR/frontend/src/componets/ExtractDataHeader.tsx, OCR/frontend/src/componets/ExtractStepper.tsx, OCR/frontend/src/componets/ExtractUploadFile.tsx, OCR/frontend/src/main.tsx, OCR/frontend/src/pages/AnnotateTemplate.tsx, OCR/frontend/src/pages/ExtractProcess.tsx, OCR/frontend/src/pages/ExtractUpload.tsx, OCR/frontend/src/utils/constants.ts
https://github.com/orgs/CDCgov/projects/33?pane=issue&itemId=75358242
=> Extract data skeleton

OCR/frontend/src/componets/Header.tsx, OCR/frontend/src/componets/tests/Header.test.tsx, OCR/frontend/src/contexts/FilesContext.tsx, OCR/frontend/src/main.tsx, OCR/frontend/src/pages/AnnotateTemplate.tsx, OCR/frontend/src/pages/SaveTemplate.test.tsx, OCR/frontend/src/pages/SaveTemplate.tsx, OCR/frontend/src/pages/UploadTemplate.tsx
- adds new save template page
- updates the header to be more reusable with title prop
- adds unit tests
https://github.com/CDCgov/IDWA/issues/183
=> feat(183): Save template page

OCR/.dockerignore, OCR/Dockerfile, OCR/README.md, OCR/ocr/api.py, OCR/pyproject.toml
Create a docker container for the OCR API
#180
- **Note first run will take a while to download the huggingface models** (1.5GB), I tired to incorporate that into the image building step by using the `huggingface cli`, sadly I needed an API key for that, will have to delay that for a dedicated story.
```shell
RUN pip install "huggingface_hub[cli]"
RUN huggingface-cli download microsoft/trocr-large-printed
```
to test the container, build and run with the following commands
```shell
docker build -t ocr .
docker run -p 8000:8000 ocr
```
then access on http://localhost:8000/docs
=> add docker integration

OCR/frontend/package-lock.json, OCR/frontend/package.json, OCR/frontend/src/componets/ImageAnnotator.tsx, OCR/frontend/src/contexts/AnnotationContext.tsx, OCR/frontend/src/contexts/FilesContext.tsx, OCR/frontend/src/pages/AnnotateTemplate.tsx, OCR/frontend/src/pages/SaveTemplate.test.tsx, OCR/frontend/src/pages/SaveTemplate.tsx
- adds local storage persistance for the templates
[Project Link](https://github.com/orgs/CDCgov/projects/33/views/1?pane=issue&itemId=75349542)
=> feat(190): Update for local storage persistance in templates form

OCR/frontend/src/pages/SaveTemplate.tsx
Previously adding a new template would overwrite all existing ones in the localStorage DB, this change persists those in addition to the new one. 
=> Allow for multiple templates to be saved rather than just the last one

OCR/frontend/index.html, OCR/frontend/src/components/AppHeader/AppHeader.tsx
update product name to ReportVision
=> update product name to ReportVision

OCR/frontend/api/api.ts, OCR/frontend/api/types/types.ts, OCR/frontend/package-lock.json, OCR/frontend/package.json, OCR/frontend/src/components/ImageAnnotator.tsx, OCR/frontend/src/components/LoadingWrapper.scss, OCR/frontend/src/components/LoadingWrapper.tsx, OCR/frontend/src/contexts/AnnotationContext.tsx, OCR/frontend/src/contexts/FilesContext.tsx, OCR/frontend/src/pages/AnnotateTemplate.tsx, OCR/frontend/src/pages/ExtractProcess.tsx, OCR/frontend/src/pages/SaveTemplate.test.tsx, OCR/frontend/src/pages/SaveTemplate.tsx, OCR/frontend/src/utils/utils.ts, OCR/ocr/api.py
github issue 185
part 1 of pr
loading spinner and api integration without, add cors
next part for part 2 will include 
PDF image below and cors integration
=> feat(185): Add extraction page with part 1 of integration

OCR/ocr/api.py, OCR/tests/api_test.py
add base64 file support for the api
=> Update api to support base64 files

OCR/frontend/src/types/models.ts
Add in initial pass at data models based on dev meeting
=> Add Data Models

OCR/frontend/eslint.config.js, OCR/frontend/package-lock.json, OCR/frontend/package.json
Inline styles are not great, this has the linter emit an error when you use them.
=> Change Linter Config to disallow inline styles

OCR/frontend/.env.local, OCR/frontend/.gitignore, OCR/frontend/api/api.ts, OCR/frontend/api/types/types.ts, OCR/frontend/e2e/ReviewTemplate.spec.ts, OCR/frontend/package-lock.json, OCR/frontend/package.json, OCR/frontend/src/components/ExtractUploadFile.tsx, OCR/frontend/src/components/ImageAnnotator.tsx, OCR/frontend/src/contexts/FilesContext.tsx, OCR/frontend/src/pages/AnnotateTemplate.tsx, OCR/frontend/src/pages/ExtractProcess.tsx, OCR/frontend/src/pages/ReviewTemplate.tsx, OCR/frontend/src/utils/utils.ts, OCR/ocr/api.py
- api implementation
- pdf displays on processing page
part 3
185
=> feat(185): Add api implementation

.github/pull_request_template.md
We haven't been filling out the PR template - this updates it to be a smaller set of questions that we can more reliably handle.
N/A (This PR uses the new template)
N/A
=> Simplify the PR Template

frontend/.env.local, frontend/api/api.ts, frontend/src/components/ImageAnnotator.tsx
- Env var naming has to be prefixed with `VITE_`
=> feat(No-id): Fix env var naming

dev-env.yaml
Minor changes to support the new folder structure in the repo in the dockerized dev environment
N/A
N/A
=> Update Dockerized Dev Env for structure changes

frontend/src/components/ImageAnnotator.tsx, frontend/src/constants/labels.ts, frontend/src/pages/AnnotateTemplate.tsx
- remove transparency for ocr pipeline
=> feat(No-id): Fix colors

.github/workflows/build-deploy-frontend.yml, frontend/.env.dev, frontend/api/api.ts
connect frontend to ocr api in dev env
#269
=> connect frontend to ocr api in dev env

.github/workflows/build-deploy-frontend.yml, OCR/ocr/api.py
update allowed origins to all for now
=> update allowed origins to all for now

frontend/api/api.ts, frontend/src/main.tsx
=> add vite env variables logs

frontend/src/pages/ReviewTemplate.tsx
The large number of numbers post decimals isn't helpful, this provides some formatting and rounds to 2 decimals
=> Add number formatting for confidence values

frontend/src/pages/ReviewTemplate.tsx
Based on feedback from Pri, round to nearest whole number, add percentage symbol
=> Update Confidence Format

.github/workflows/build-deploy-ocr.yml, .github/workflows/build-ocr-docker.yml
Creating this to unblock ocr api deployments. This works for one environment at a time but we will want to have this deployed from Terraform in the future so we can better control each environment being made
=> Temporarily deploy ocr api from Github Action

OCR/Dockerfile, OCR/poetry.lock, OCR/pyproject.toml
fix OCR dependencies by adding necessary ones, will revisit in the future
=> fix OCR dependencies

frontend/api/api.ts, frontend/eslint.config.js, frontend/src/components/ImageAnnotator.tsx, frontend/src/components/TemplatesIndex/TemplatesIndex.tsx, frontend/src/contexts/AnnotationContext.test.tsx, frontend/src/contexts/AnnotationContext.tsx, frontend/src/contexts/FilesContext.tsx, frontend/src/main.tsx, frontend/src/pages/AnnotateTemplate.tsx, frontend/src/pages/ExtractProcess.tsx, frontend/src/pages/SaveTemplate.test.tsx, frontend/src/pages/SaveTemplate.tsx, frontend/src/utils/functions.ts
- create canvas and new png screen shots 
- remove old annotation old
=> feat(264): Fix FE segmentation

.github/workflows/build-deploy-ocr.yml, ops/terraform/modules/app_service/main.tf
Makes our temporary ocr-api build and deploy more flexible and fast if we need to rollback or change versions for dev reasons.
=> Check if ocr-api image is already registered, If it is skip build and deploy

frontend/src/App.scss, frontend/src/App.tsx, frontend/src/pages/ReviewTemplate.tsx
- Adjust side nav width
- remove underline for links in side nav
=> fix(285): Fix sidenav width and nav links

.github/workflows/build-deploy-frontend.yml
=> hotfix for endpoint naming issue

.github/workflows/build-deploy-ocr.yml
cause it only works for registered only apparently..
=> FIX: Remove docker registered image check

backend/dev-dockerfile, backend/src/main/resources/application.yaml, dev-env.yaml
Builds a live reloading instance of the api service for development. You will need to build the java code (`./gradlew build`) but then the server will pick up the changes.
N/A
N/A - Dev environment simplification
=> Add API service to Docker

.github/workflows/deploy-dev.yml
Forgot to add demo to the options list in for this workflow. we can't run the demo env without it.
=> Add demo name to deploy options list

.github/actions/tf-setup/action.yml
whoops forgot to add this var to to tfvars. this tells azure how big of a compute instance we need.
=> Forgot to add sku_name to tfvars

frontend/src/components/TemplatesIndex/TemplatesIndex.tsx, frontend/src/pages/ExtractProcess.tsx
- improve user flow to only have single submit
=> fix(328): Update to only have a single submit

frontend/e2e/ReviewTemplate.spec.ts, frontend/src/pages/ReviewTemplate.tsx
Removes the isError column from display now that the icon is over in the field per designs.
=> Fixes warning icon column appearance

.github/workflows/build-deploy-frontend.yml, .github/workflows/deploy-dev.yml, ops/terraform/config/dev2.config, ops/terraform/config/dev3.config, ops/terraform/config/dev4.config, ops/terraform/config/dev5.config, ops/terraform/config/dev6.config, ops/terraform/locals.tf, ops/terraform/main.tf
This doesn't change anything logically, it just cleans up things to make it more readable and look good for if anybody takes our project over in the future.
=> Remove unneeded Resource Groups and creds

backend/src/main/java/gov/cdc/ReportVision/models/BaseEntity.java, backend/src/main/java/gov/cdc/ReportVision/models/Template.java, frontend/e2e/App.spec.ts, frontend/src/App.tsx, frontend/src/components/ExtractUploadFile.tsx, frontend/src/components/TemplatesIndex/TemplatesIndex.tsx, frontend/src/components/tests/ExtractStepper.test.tsx, frontend/src/components/tests/ExtractUploadFile.test.tsx, frontend/src/main.tsx, frontend/src/types/models.ts, frontend/src/types/templates.ts, frontend/src/utils/tests.tsx
Templates will be loaded from the java API which is assumed to be running at `MIDDLEWARE_API_URL` or `localhost:8081
No visual differences
#296
=> Load Templates from Backend DB via Java API

backend/src/main/java/gov/cdc/ReportVision/models/ApiUser.java, backend/src/main/java/gov/cdc/ReportVision/models/BaseEntity.java, backend/src/main/java/gov/cdc/ReportVision/models/Template.java
Per discussion, this will include the user and org info in the responses for templates if it is set.
N/A No visual changes
N/A Just came up in retro
=> Add CreatedBy and UpdatedBy Info Into Response

ops/terraform/main.tf, ops/terraform/modules/database/main.tf, ops/terraform/modules/database/variables.tf
just a quick add to allow for multi environment setups
=> Add environment var to db module

frontend/src/components/ExtractUploadFile.scss, frontend/src/components/ExtractUploadFile.tsx, frontend/src/components/ReviewBulk.tsx, frontend/src/contexts/FilesContext.tsx, frontend/src/pages/SaveTemplate.tsx
add error for different number of pages
=> feat(RV-390): Add error check for template and document page mismatch

frontend/src/components/Header.tsx, frontend/src/pages/__snapshots__/UploadTemplate.test.tsx.snap
disable the button for next for template creation
=> fix(RV-390): Fix annotation template disable

frontend/src/components/ExtractUploadFile.tsx, frontend/src/contexts/FilesContext.tsx, frontend/src/utils/functions.ts
Disable extract button when error is there
=> fix(RV-no-id): Add disable logic when error is present

frontend/src/pages/ExtractProcess.tsx
- updates loading string to new [figma](https://www.figma.com/design/1FW8ZSDV90q2wpRPOADE9r/ReportVision?node-id=1630-11359&node-type=frame&t=AkDDyocNzEGS9Z7H-0)
=> feat(RV-435): Updates to loading string

frontend/e2e/ReviewTemplate.spec.ts, frontend/src/components/ExtractDataHeader.tsx, frontend/src/components/Header.tsx, frontend/src/components/ReviewBulk.tsx, frontend/src/pages/ExtractUpload.tsx, frontend/src/pages/UploadTemplate.tsx, frontend/src/pages/__snapshots__/UploadTemplate.test.tsx.snap
=> fix(RV-436): Adjust cta to only have one for screens

ops/terraform/main.tf
=> hotfix API's depend on subnets

frontend/src/components/ImageAnnotator.tsx, frontend/src/components/LoadingWrapper.scss
- Adjust size for common screen sizes
=> fix(RV-429): Adjust page cutoff for image annatator

frontend/src/App.test.tsx, frontend/src/App.tsx
Fix for previous files getting displayed in extraction flow
=> fix(RV-440): Fix file bug where prev files are displayed

frontend/api/api.ts
=> updated url

frontend/api/api.ts
=> add url change

frontend/e2e/App.spec.ts, frontend/src/components/TemplatesIndex/TemplatesIndex.tsx, frontend/src/pages/SaveTemplate.tsx
=> fix(RV-394): Update template redesign

frontend/api/api.ts
=> updated middleware URL

frontend/api/api.ts, frontend/src/types/templates.ts
=> updated middleware URL (2)

frontend/api/api.ts
=> removed slash

frontend/src/components/UploadFile.tsx
The cancel button was going to a 404. Fixed the cancel button to back to root of the app.
=> fixed cancel button on upload page

.github/actions/tf-setup/action.yml
=> Change SKU for lower cost but hopefully better performance

.github/actions/tf-setup/action.yml
The V needs to be lower case I'm pretty sure. We get the below error because of it when the workflow runs.
=> Hot fix sku size naming convention

frontend/src/pages/AnnotateTemplate.tsx
create single set to track unique fields across pages
=> fix(RV-431): Fix multiple page uniqueness for fields

frontend/src/App.test.tsx, frontend/src/App.tsx, frontend/src/components/ExtractUploadFile.scss, frontend/src/components/TemplatesIndex/TemplatesIndex.tsx, frontend/src/contexts/FilesContext.tsx
Templates should determine new screens are shown
=> fix(RV-497): Fix 1st time ux to templates > 0

frontend/src/components/ExtractUploadFile.tsx
=> fix(Rv-no-id): Fix error

docs/user_guide.md
=> [Guide] remove relative links

docs/user_guide.md
=> Update links for user guide infra

frontend/README.md
=> doc(RV-507): Add update to frontend readme
